### PR TITLE
refactor baf dll to external folder

### PR DESCRIPTION
**Pull request by SteffenHeu**

### CODE REVIEW

**Review by robinschmid — CHANGES_REQUESTED** [review]
Does not work when run from intellij

```
SEVERE: Unhandled exception java.lang.ExceptionInInitializerError while processing task Importing file ToxMix_FreiburgOptifinal_AutoMSMS_scanning9Hz_2_1_1_22114.d - 0/0
java.lang.ExceptionInInitializerError
	at io.github.mzmine.modules.io.import_rawdata_bruker_baf.library.baf2sql.BafDataAccess.<init>(BafDataAccess.java:71)
	at io.github.mzmine.modules.io.import_rawdata_bruker_baf.library.BafImportTask.run(BafImportTask.java:107)
	at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:166)
	at io.github.mzmine.taskcontrol.threadpools.ThreadPoolTask.lambda$trackProgressTask$3(ThreadPoolTask.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.IllegalArgumentException: Cannot open library: external_tools/bruker_baf/baf2sql_c.dll
	at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:314)
	at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:266)
	at io.github.mzmine.modules.io.import_rawdata_bruker_baf.library.baf2sql.BafLib.<clinit>(BafLib.java:98)
	```

**Comment by SteffenHeu** [comment]
Whats the working directory of your run configuration?

**Comment by robinschmid** [comment]
ok was the wrong directory

**Review by robinschmid — APPROVED** [review]
Works like expected with the correct run directory

**Pull request merged**
